### ISSUE TITLE
Missing export types `Roi.ts`

### ISSUE THREAD

**Issue by tpoisseau** [zakodium-oss/react-roi#146]
`src/types/Roi.ts`

Members of this file should be exported from `src/index.ts`

**Comment by tpoisseau** [comment]
`getScanRoiStyle` method for document anonymization into our main internal project

**Comment by stropitek** [comment]
> `getScanRoiStyle` method for document anonymization into our main internal project

but this seems unrelated to the types [src/types/Roi.ts](https://github.com/zakodium-oss/react-roi/blob/bfa3a22617eb06be994602ea73735ebe8b05987b/src/types/Roi.ts) exports

**Comment by tpoisseau** [comment]
No, this method use this path import (`import { Roi } from 'react-roi/src/types/Roi';`)

**Comment by stropitek** [comment]
Superseeded by https://github.com/zakodium-oss/react-roi/issues/147
