### ISSUE TITLE
How to access the state and dispatch in the component?

### ISSUE THREAD

**Issue by josoriom** [zakodium-oss/react-roi#18]
@stropitek  It seems that the current approach I'm using to access the state and dispatch is likely incorrect. I'm getting this ESLint error:

```
The object passed as the value prop to the Context provider (at line 248) changes every render. To fix this consider wrapping it in a useMemo hook.
```

https://github.com/zakodium-oss/react-roi/blob/3aaf1256db8166cda34f6781c0ba8bd1e73b7e07/src/context/RoiContext.tsx#L244-L253

**Comment by stropitek** [comment]
You can use the recommended fix.

But I recommend splitting into 2 contexts / providers. Render 1 provider for the state and 1 for the dispatch. This way any component which only needs to dispatch will not get unnecessarily re-rendered since the dispatch function is a stable reference.
