### ISSUE TITLE
Rename "pointers" / "corners" properties?

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-roi#23]
I did not do the change because I am not sure `p0` and `p1` refer to specific corners of the rectangle, like "upper left" and "bottom right".

![CleanShot 2023-08-18 at 11 59 15](https://github.com/zakodium-oss/react-roi/assets/4118690/eacce317-06f9-47dd-9d4d-24692c672ce8)

@josoriom Do you have a more meaningful name for those properties?

**Comment by josoriom** [comment]
`p0` and `p1` are opposite corners, and the outcome depends on which corner you choose. If top-left corner, p0 represents is top-left, while p1 would be the bottom-right. if top-right corner, p0 indicates the top-right, and p1 would be the bottom-left.

About the names `startPoint` and `endPoint`?
