### ISSUE TITLE
Clicking update in demo is buggy

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-roi#39]
It does not move the same way in the "live" rois and in the commited rois

**Comment by stropitek** [comment]
https://github.com/zakodium-oss/react-roi/assets/4118690/9201df90-976c-4f2a-b65e-ab7134e1d7ac

The coordinates of the committed ROIs are wrong once we update, but correct once we re-select the roi.

**Comment by josoriom** [comment]
@stropitek The sizes accepted by actions correspond to `committedRois`. It was updating the `roi` using `updatedData` with the size of `committedRoi`. Resizing before updating will fix the problem.
