### ISSUE TITLE
Unexpected behavior due to css properties

### ISSUE THREAD

**Issue by josoriom** [zakodium-oss/react-roi#45]
Some CSS properties, like padding and margin, might lead to undesired component behavior

![image](https://github.com/zakodium-oss/react-roi/assets/31483796/d3524be6-0611-4900-9c6c-0cf120434761)

**Comment by stropitek** [comment]
I think the solution is simply to `Pick` allowed properties in TS

We can't prevent this when using classNames though, but it feels like common sense not to use certain properties.

**Comment by targos** [comment]
I wouldn't do anything about it. There are too many properties and as you said, it's common sense to use the ones that don't break the layout.
