### ISSUE TITLE
Corner and side handles become barely visible after a certain amount of zoom

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-roi#94]
And the handles cannot be interacted with anymore.

![CleanShot 2024-01-22 at 11 29 32](https://github.com/zakodium-oss/react-roi/assets/4118690/0b1913ec-7fd2-4fb1-85c3-9966074a5f7a)

**Comment by targos** [comment]
There should be a minimum and maybe also maximum  size for them
